### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by Airon90** [dkim0419/SoundRecorder#24]
Hi, I'd like to translate your app into Italian and Esperanto but I don't know how to do that. 
Could someone explain it in a "How to contribute" section of [README.md](https://github.com/dkim0419/SoundRecorder/blob/master/README.md)? Thank you very much!

**Comment by mary-kate** [comment]
@Airon90 First, make a copy of the repository while logged in to GitHub. To do this, go to https://github.com/dkim0419/SoundRecorder and click on the "Fork" button. Then check out your brand new fork with your favorite version control system client (command-line git binary, TortoiseGit on Windows...or even TortoiseSVN!).

Then, under the `SoundRecorder/app/src/main/res` directory, you'll need to create the appropriate directories for each translation -- `values-it` for Italian and `values-eo` for Esperanto. Then you need to copy the file `strings.xml` from `SoundRecorder/app/src/main/res/values` into the newly-created directories. Open up the copied `strings.xml` files (i.e. `SoundRecorder/app/src/main/res/values-it/strings.xml` and `SoundRecorder/app/src/main/res/values/values-eo/strings.xml`) and start translating!

Once that's done, you're able to submit a pull request by going to your fork's page on GitHub (i.e. https://github.com/Airon90/SoundRecorder) and clicking on the small green icon next to the branch list menu.

However...you should note that right now there are seven open pull requests against this repository, six of which concern translations. @dkim0419, are you still around and maintaining this app? Because if you are, it would be lovely if you could close some of these pull requests. Thanks. :)

**Comment by Airon90** [comment]
Ok, I won't do anything until @dkim0419's answer.
Thank you!

**Comment by dkim0419** [comment]
Haven't been able to keep up with the app recently, but I have merged all of the pull requests related to translations today. Thanks @mary-kate for the detailed answer too!

@Airon90 italian and esperando translations would be great! thanks!

i can push a play store update with all the new translations all together in the near future
